CREATE TABLE [dbo].[Comments]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Text] NVARCHAR(250) NULL, 
    [NewId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_Table_ToNews] FOREIGN KEY ([NewId]) REFERENCES [News]([Id]))